### ISSUE TITLE
Replace Travis CI with functioning CI for this repo

### ISSUE THREAD

**Issue by wbobeirne** [sapio-lang/bitcoin-core-ts#5]
Accepting PRs will be a lot easier if types are checked and tests are run on them. It looks like there's a travis.yml that's likely defunct now, probably easiest to port to Github actions since as far as I'm aware, Travis has undergone a lot of weird changes since their acquisition in 2019.

**Comment by JeremyRubin** [comment]
ack on upgrading for functional CI
